#!/bin/bash
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/0.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/0.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/0.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/0.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/0.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/1.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/1.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/1.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/1.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/1.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/2.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/2.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/2.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/2.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/2.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/3.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/3.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/3.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/3.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/3.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/4.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/4.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/4.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/4.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/4.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/5.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/5.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/5.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/5.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/5.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/6.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/6.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/6.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/6.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/6.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/7.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/7.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/7.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/7.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/7.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/8.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/8.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/8.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/8.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/8.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/9.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/9.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/9.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/9.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/FR/9.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/0.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/0.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/0.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/0.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/0.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/1.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/1.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/1.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/1.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/1.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/2.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/2.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/2.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/2.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/2.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/3.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/3.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/3.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/3.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/3.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/4.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/4.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/4.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/4.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/4.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/5.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/5.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/5.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/5.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/5.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/6.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/6.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/6.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/6.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/6.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/7.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/7.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/7.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/7.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/7.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/8.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/8.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/8.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/8.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/8.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/9.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/9.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/9.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/9.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/HU/9.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/0.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/0.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/0.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/0.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/0.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/1.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/1.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/1.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/1.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/1.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/2.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/2.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/2.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/2.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/2.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/3.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/3.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/3.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/3.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/3.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/4.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/4.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/4.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/4.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/4.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/5.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/5.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/5.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/5.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/5.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/6.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/6.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/6.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/6.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/6.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/7.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/7.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/7.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/7.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/7.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/8.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/8.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/8.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/8.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/8.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/9.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/9.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/9.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/9.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/9.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/0.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/0.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/0.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/0.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/0.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/1.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/1.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/1.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/1.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/1.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/2.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/2.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/2.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/2.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/2.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/3.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/3.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/3.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/3.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/3.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/4.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/4.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/4.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/4.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/4.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/5.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/5.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/5.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/5.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/5.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/6.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/6.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/6.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/6.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/6.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/7.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/7.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/7.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/7.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/7.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/8.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/8.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/8.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/8.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/8.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/9.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/9.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/9.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/9.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/9.output.jck.txt
