#!/bin/bash
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/5.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/5.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/5.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/5.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/5.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/6.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/6.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/6.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/6.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/6.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/7.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/7.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/7.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/7.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/7.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/8.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/8.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/8.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/8.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/8.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/9.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/9.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/9.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/9.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/CS/9.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/0.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/0.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/0.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/0.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/0.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/1.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/1.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/1.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/1.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/1.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/2.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/2.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/2.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/2.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/2.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/3.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/3.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/3.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/3.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/3.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/4.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/4.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/4.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/4.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/4.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/5.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/5.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/5.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/5.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/5.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/6.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/6.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/6.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/6.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/6.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/7.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/7.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/7.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/7.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/7.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/8.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/8.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/8.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/8.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/8.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/9.train.jck.txt -tag-morph false -model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/9.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/9.model.jck.txt --test-file form-index=0,/Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/9.test.jck.txt --pred-file /Users/halsaied/Documents/IdenSys/MarMot/Jackkniffing/PL/9.output.jck.txt
