import json
import os

class Parameters:
    xpName = ''
    configPath = 'Config'
    languageName = ''
    projectPath = os.path.dirname(__file__)[:-len(os.path.basename(os.path.dirname(__file__)))]
    configPath = os.path.join(projectPath, configPath)

    readMe = os.path.join(projectPath, "Results/readMe.md")
    results = os.path.join(projectPath, "Results/results.csv")
    corpusPath = os.path.join(projectPath, "sharedtask/")
    xpPath = os.path.join(projectPath, "Results/")
    langFolder = os.path.join(projectPath, "Results/")
    resultPath = os.path.join(projectPath, "Results/")

    includeEmbedding = True
    useAutoGeneratedPOS = True
    useAutoGeneratedDEP = True

    printSentsWithEmbeddedMWEs = False
    printFeaturesOfSent = False

    realExper = False
    useCrossValidation = False

    usePreciseDictionary = False


    printReport = True
    serialize = True

    # Featue extraction parameters
    useFirstBufferElement = True
    useSecondBufferElement = True
    useToken = True
    useLemma = True
    usePOS = True
    useBiGram = True
    useTriGram = True
    useDistance = True
    useSyntax = True

    generateS0B2Bigram = True
    useDictionary = True

    historyLength1 = True
    historyLength2 = True
    historyLength3 = True
    useS0B0Distance = True
    useS0S1Distance = True
    useStackLength = True

    enhanceMerge = False
    enableSingleMWE = False
    useLexic = False

    generateS1B1 = False

    NumOFSent = '### Number of Sentences: '
    NumOFMWEs = '\n### Number of MWEs: '
    NumOFEmbedded = '\n### Number of Embedded MWEs: '
    NumOFInterleaving = '\n### Number of Interleaving MWEs: '
    NumContinousMWEs = '\n### Number of Continous MWEs: '
    NumSingleWordMWEs = '\n### Number of Single Word MWEs: '

    def __init__(self, filePath, corpus=None):

        with open(filePath, 'r') as configFile:
            config = json.load(configFile)

            if len(filePath.split('/')) > 0:
                Parameters.xpName = filePath.split('/')[-1].split('.')[0]
            Parameters.configPath = filePath

            if "generateS1B1" in config.keys():
                Parameters.generateS1B1 = config["generateS1B1"]

            if "enhanceMerge" in config.keys():
                Parameters.enhanceMerge = config["enhanceMerge"]

            if "usePreciseDictionary" in config.keys():
                Parameters.usePreciseDictionary = config["usePreciseDictionary"]

            if "useLexic" in config.keys():
                Parameters.useLexic = config["useLexic"]

            if "enableSingleMWE" in config.keys():
                Parameters.enableSingleMWE = config["enableSingleMWE"]

            Parameters.useFirstBufferElement = config["useFirstBufferElement"]
            Parameters.useSecondBufferElement = config["useSecondBufferElement"]

            Parameters.usePOS = config["UseLinguistInfo"]["usePOS"]
            Parameters.useLemma = config["UseLinguistInfo"]["useLemma"]
            Parameters.useBiGram = config["UseLinguistInfo"]["useBiGram"]
            Parameters.useTriGram = config["UseLinguistInfo"]["useTriGram"]

            Parameters.useS0B0Distance = config["S0B0Distance"]
            Parameters.useS0S1Distance = config["S0S1Distance"]
            Parameters.useStackLength = config["useStackLength"]
            Parameters.useSyntax = config["UseLinguistInfo"]["useSytax"]
            Parameters.generateS0B2Bigram = config["generateS0B2Bigram"]

            Parameters.useDictionary = config["useDictionary"]

            Parameters.historyLength1 = config["useTransitionHistory"]["transitionHistoryLength1"]
            Parameters.historyLength2 = config["useTransitionHistory"]["transitionHistoryLength2"]
            Parameters.historyLength3 = config["useTransitionHistory"]["transitionHistoryLength3"]

        Parameters.createXPFolder()
        Parameters.createConfigAndReadMe(corpus)

    @staticmethod
    def createXPFolder():
        # xpFolder = Parameters.toBinary()
        if Parameters.printReport:
            if not os.path.exists(Parameters.xpPath):
                os.makedirs(Parameters.xpPath)


    @staticmethod
    def createConfigAndReadMe(corpus):
        if Parameters.printReport:
            staticParsingFile = open(os.path.join(Parameters.xpPath, 'config.md'), 'w')
            staticParsingFile.write(Parameters.toString())

            result = Parameters.NumOFSent + str(corpus.sentNum) + Parameters.NumOFMWEs + str(
                corpus.mweNum) + '\n' + Parameters.NumOFEmbedded + str(
                corpus.emeddedNum) + '\n' + Parameters.NumOFInterleaving + str(
                corpus.intereavingNum) + '\n' + Parameters.NumContinousMWEs + str(
                corpus.continousExp) + '\n' + Parameters.NumSingleWordMWEs + str(corpus.singleWordExp)
            printingPath = os.path.join(Parameters.xpPath, 'Readme.md')
            staticParsingFile = open(printingPath, 'w')
            staticParsingFile.write(result)

    @staticmethod
    def toBinary():

        if Parameters.configPath == '':
            return ''
        result = ''
        with open(Parameters.configPath, 'r') as configFile:
            config = json.load(configFile)
            for key in config.keys():
                if isinstance(config[key], bool):
                    if config[key]:
                        result += '1'
                    else:
                        result += '0'
                elif isinstance(config[key], dict):
                    for subkey in config[key].keys():
                        if isinstance(config[key][subkey], bool):
                            if config[key][subkey]:
                                result += '1'
                            else:
                                result += '0'

        return result

    @staticmethod
    def toABC():

        if Parameters.configPath == '':
            return ''
        idxs = 'ABCDEFGHIJKLMNOPQRST'
        result = ''
        with open(Parameters.configPath, 'r') as configFile:
            config = json.load(configFile)
            idx = 0
            idxxx = 0
            # print 'Nmber of Keys: ', len(config.keys())
            for key in config.keys():
                if isinstance(config[key], bool):
                    # print  idxs[idxxx: idxxx  +1], key#, config[key]
                    if config[key]:
                        result += str(idxs[idx:idx + 1]) + ' ' + key + ' '
                    idx += 1
                    idxxx += 1
                elif isinstance(config[key], dict):
                    for subkey in config[key].keys():
                        if isinstance(config[key][subkey], bool):
                            # print idxs[idxxx: idxxx  +1], subkey #, config[key][subkey]
                            if config[key][subkey]:
                                result += str(idxs[idx:idx + 1]) + ' ' + subkey + ' '
                        idx += 1
                        idxxx += 1

        # print result
        return result

    @staticmethod
    def toString():
        if Parameters.configPath == '':
            return ''
        result = ''
        with open(Parameters.configPath, 'r') as configFile:
            config = json.load(configFile)
            for key in config.keys():
                if isinstance(config[key], bool):
                    result += str(key)
                    if config[key]:
                        result += ' = True\n\n'
                    else:
                        result += ' = False\n\n'

                elif isinstance(config[key], dict):
                    for subkey in config[key].keys():
                        if isinstance(config[key][subkey], bool):
                            result += str(subkey)
                            if config[key][subkey]:
                                result += ' = True\n\n'
                            else:
                                result += ' = False\n\n'
        return result


for subdir, dirs, files in os.walk('Done'):
    for dir in dirs:
        for subdir1, dirs1, configFiles in os.walk(os.path.join('Done', dir)):
            for configFile in configFiles:
                if not configFile.endswith('.json'):
                    continue
                Parameters.configPath = os.path.join(os.path.join('Done', dir), configFile)
                print Parameters.toABC()
